---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Wait for systemd to complete initialization.  
      command: systemctl is-system-running
      register: systemctl_status
      until: >-
        "running" in systemctl_status.stdout or "degraded" in
        systemctl_status.stdout
      retries: 30
      delay: 5
      when:
        - ansible_service_mgr == "systemd"
        - ansible_distribution == "Fedora"
      changed_when: false
    - name: Update package cache
      package: update_cache=yes
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
  #roles:
  #  - role: java
- import_playbook: ../../java.yaml

  vars:
        # Define Agent Type and Version 
        agent_version: 20.6.0
        agent_type: sun-java
        # The applicationName
        application_name: "IoT_API"
        tier_name: "login_service2" # ONLY required if agent type is not machine and db agent
        application_environment: "production"
        # Your controller details 
        controller_account_access_key: "ffdsfs" # Please add this to your Vault 
        controller_host_name: "saas.appdynamics.com" # Your AppDynamics controller 
        controller_account_name: "customer1"  # Please add this to your Vault 
        ssl_enabled: false
        controller_port: "443"